{% set version = "0.3.32" %}

package:
  name: fmpy
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/py3/f/fmpy/fmpy-{{ version }}-py3-none-any.whl
  sha256: b379deb9417b842028003a288d00c1c5f138d1580e1ff12cc6c42a98719cecf0
  # macOS: shasum -a 256 <file>
  # Windows: certutil -hashfile <file> SHA256

build:
  number: 0
  entry_points:
    - fmpy = fmpy.command_line:main

outputs:

  - name: fmpy-base
    script: build_base.bat  # [win]
    script: build_base.sh  # [not win]
    requirements:
      host:
        - python >={{ python_min }}
        - pip
        - setuptools
      run:
        - python >={{ python_min }}
        - attrs
        - jinja2
        - lark
        - lxml
        - msgpack-python
        - numpy
        - pywin32  # [win]
    test:
      requires:
        - python {{ python_min }}
      imports:
        - fmpy
        - fmpy.cross_check
        - fmpy.examples
        - fmpy.container_fmu
        - fmpy.ssp
        - fmpy.sundials  # [not unix]

  - name: fmpy
    build:
      noarch: python
    requirements:
      host:
        - python {{ python_min }}
      run:
        - python >={{ python_min }}
        - dash-bootstrap-components >=1.0.0
        - dask
        - matplotlib-base
        - notebook
        - plotly
        - pyqt
        - pyqtgraph
        - pyqtwebengine
        - python-kaleido
        - requests
        - scipy
        - {{ pin_subpackage('fmpy-base', max_pin="x.x.x") }}
    test:
      requires:
        - python {{ python_min }}
      imports:
        - fmpy.gui
        - fmpy.webapp

about:
  home: https://github.com/CATIA-Systems/FMPy
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Simulate Functional Mockup Units (FMUs) in Python
  doc_url: https://fmpy.readthedocs.io/
  dev_url: https://github.com/CATIA-Systems/FMPy

extra:
  recipe-maintainers:
    - t-sommer
    - wulmer
    - jschueller
